const Local = () => {
	return (
		<>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
			<div>Local</div>
		</>
	);
};

export default Local;
